import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { allPosts } from ".contentlayer/data";

const Home = (props: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Posts</h1>
        {
          props.posts.map((post: any) => {
            return (
              <Link key={post.slug} href={`/blog/${post.slug}`} passHref>
                <a>{post.title}</a>
              </Link>
            )
          })
        }
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const posts = allPosts;

  return {
    props: {
      posts,
    },
  };
}
export default Home;
